Compute quaternion rotating a vector into another
recp/cglm pull request #210
Opened 2021-06-10 17:45 UTC by legends2k

* Given two unit `vec3`s, compute versor that would rotate `a` into `b`
* Add tests for verify following cases
  - Parallel
  - Perpendicular
  - Straight
  - Random
  - Acute
  - Obtuse
  - Zero

2021-06-14 06:04 UTC, legends2k commented
@recp Note: this PR (creating a quaternion from two vectors) is unrelated and different from [the previous one][1] (rotating a vector using quaternion).

Once this PR is in, I'll create another PR for resolving the unit axes issue.  It'll make all functions taking an input axes into unit axes and also update documentation.

[1]: https://github.com/recp/cglm/pull/206

2021-06-14 10:32 UTC, recp commented
@legends2k sorry for the late response,

We already have `glm_quat_for()` and `glm_quat_for()`, are there any differences with them?

2021-06-14 11:33 UTC, legends2k commented
> We already have `glm_quat_for()` and `glm_quat_forp()`, are there any differences with them?

Existing `glm_quat_for` is used to compute an [orthonormal basis][] for entities like camera.  The rotation needed to go from current space to such space would be encoded in the destination quaternion.  It takes forward and up vectors as inputs, generates a side vector and forms such a basis.

This function is different; it just gives the rotation between two vectors.  Say a model is looking towards <0.707, 0.707, 0> and we want it to look towards <0, 1, 0>, feeding these two vectors would give the needed rotation as a quaternion.  The existing function would not do this; it's simply for a different purpose.

[orthonormal basis]: https://en.wikipedia.org/wiki/Orthonormal_basis

2021-06-14 12:38 UTC, recp commented
@legends2k great! 

Can you declare all variables at the beginning of func/block like (https://github.com/recp/cglm/blob/master/CONTRIBUTING.md):

```C
void
func() {
  float variable1, variable2;
  int   variable3;

  variable1 = 123.0f;
}
```

2021-06-14 12:42 UTC, recp requested changes

2021-06-14 12:42 UTC, recp commented on include/cglm/quat.h
> +    const float cos_zero = 1.0f;
I think there is no need to create separate consst variable. Float literal woul also be a constant: `1.0f + cos_theta`

2021-06-14 12:42 UTC, recp commented on include/cglm/quat.h
> +  else {
No new-line for else pls.

2021-06-14 12:42 UTC, recp commented on include/cglm/quat.h
> +  if (cos_theta < -1.f + GLM_FLT_EPSILON) {  // angle(a, b) = 180°
C89 style comment pls e.g `/*  */`

2021-06-15 13:33 UTC, legends2k commented on include/cglm/quat.h
> +  else {
Done!

2021-06-15 13:34 UTC, legends2k commented
> @legends2k great!
> 
> Can you declare all variables at the beginning of func/block like (https://github.com/recp/cglm/blob/master/CONTRIBUTING.md):

Done!

2021-06-15 13:34 UTC, legends2k commented on include/cglm/quat.h
> +  if (cos_theta < -1.f + GLM_FLT_EPSILON) {  // angle(a, b) = 180°
Done!

2021-06-15 13:48 UTC, legends2k commented
@recp Incorporated PR comments, please check now :)

2021-06-15 16:59 UTC, merged

2021-06-15 17:00 UTC, recp commented
@legends2k many thanks 👏 the pr is merged